### ISSUE TITLE
print function is not working properly inside while loop

### ISSUE THREAD

**Issue by vikas1369** [fivdi/lcd#14]
Hi,
I am new to nodejs and what I have done is I have connected LCD Panel and 4x4 Membrane matrix keypad to Raspberry Pi and I have programmed them using Node.js. What I want to achieve is whenever a key is pressed it should be displayed immediately on the LCD panel and when I press # it should stop taking input.

For this I have used packages LCD and RPIO and since I have to continuously check for user input I have put the code for taking input in while loop & inside that I have written the print statement and that is where the problem is coming. LCD panel doesn't display any character when I press a key on keypad but when I press #, the program exits and all the characters are displayed on the LCD panel.

The code that I have written is as follows.

```js
var rpio = require('rpio');
rpio.open(3, rpio.OUTPUT, rpio.LOW);
var Lcd = require('lcd'),
  lcd = new Lcd({
    rs: 18,
    e: 23,
    data: [24, 17, 27, 22],
    cols: 8,
    rows: 2
  });
var matrix=[[1,2,3,'A'],
	    [4,5,6,'B'],
	    [7,8,9,'C'],
	    ['*',0,'#','D']]
var row=[37,35,33,31];
var col=[29,23,40,38];
for (var i = 0; i < 4; i++) {
      rpio.open(col[i], rpio.OUTPUT, rpio.HIGH);
}
for (var i = 0; i < 4; i++) {
      rpio.open(row[i], rpio.INPUT, rpio.PULL_UP);
}
var code="";
var comeout=0;
lcd.on('ready', function() {
    lcd.setCursor(0, 0);
    //start of keypad code
    while(true){
	for (var j = 0; j < 4; j++) {
		rpio.write(col[j],rpio.LOW);
		for (var i = 0; i < 4; i++) {
			if(rpio.read(row[i])==0){
			console.log(matrix[i][j]);
  			lcd.print(matrix[i][j]);
			if(matrix[i][j]=='#'){
				comeout=1;
				break;
			}
			while(rpio.read(row[i])==0);
			}	
		}
		if(comeout==1)
			break;
		else
			rpio.write(col[j],rpio.HIGH);
	}
	if(comeout==1)
		break;
	}
    //end of keypad code
});
 
// If ctrl+c is hit, free resources and exit.
process.on('SIGINT', function() {
  lcd.clear();
  lcd.close();
  process.exit();
});
```

**Comment by fivdi** [comment]
Hi,

I edited the above post to format the code (use three ` at the start and end of a code block to format the code :))

You mention that you are new to Node.js. Where Node.js is very different to a lot of other environments is it's asynchronous programming model. The code in the above while loop doesn't play well with the Node.js asynchronous programming model. The loop will run until the user hits the '#' key. This is called blocking code. This type of code needs to be avoided as it prevents other asynchronous code from executing. In this case the code that it prevents from executing is the asynchronous code in the print method. When the print method is called it doesn't print the value passed and return. It puts the value passed in a queue and returns immediately. Later, when time is available, the value will be printed. However, because the while loop runs until the user hits '#' there is no time available until the loop has completed. This explains why the characters are printed after the loop terminates. The program also terminates as it has nothing else to do.

Rather than using a while loop to continuously scan the key pad until '#' is pressed, the code needs to be modified to scan the key pad at regular intervals, for example, once every 50 milliseconds.

**Comment by vikas1369** [comment]
Ohh...Using setInverval solved the issue. Thank you so much.
